wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.8
    cli_version: 0.17.0
    framework: huggingface
    huggingface_version: 4.41.2
    is_jupyter_run: true
    is_kaggle_kernel: true
    start_time: 1717146246
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 63
      2:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 49
      - 53
      - 55
      - 63
      - 103
      3:
      - 13
      - 23
      4: 3.11.8
      5: 0.17.0
      6: 4.41.2
      8:
      - 1
      - 2
      - 5
      13: linux-x86_64
