wandb_version: 1

data_dir:
  desc: null
  value: /home/disi/ml/datasets/air
dataset_name:
  desc: null
  value: air
checkpoint:
  desc: null
  value: null
save_dir:
  desc: null
  value: /home/disi/ml/checkpoints/seresnet50
project_name:
  desc: null
  value: seresnet50_prova
image_size:
  desc: null
  value: 224
num_classes:
  desc: null
  value: 102
mean:
  desc: null
  value:
  - 0.485
  - 0.456
  - 0.406
std:
  desc: null
  value:
  - 0.229
  - 0.224
  - 0.225
model_name:
  desc: null
  value: seresnet50
batch_size:
  desc: null
  value: 32
epochs:
  desc: null
  value: 5
optimizer:
  desc: null
  value: Adam
optimizer_type:
  desc: null
  value: custom
learning_rate:
  desc: null
  value: 0.001
weight_decay:
  desc: null
  value: 0.0001
momentum:
  desc: null
  value: 0
criterion:
  desc: null
  value: CrossEntropyLoss
dropout:
  desc: null
  value: 0.5
scheduler:
  desc: null
  value: true
step_size:
  desc: null
  value: 5
patience:
  desc: null
  value: 3
param_groups:
  desc: null
  value:
  - prefixes:
    - classifier
    lr: 0.001
  - prefixes:
    - features
device:
  desc: null
  value: cuda
_wandb:
  desc: null
  value:
    python_version: 3.11.8
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1716556580
    t:
      1:
      - 1
      - 41
      - 49
      - 55
      - 63
      2:
      - 1
      - 41
      - 49
      - 55
      - 63
      3:
      - 13
      - 16
      - 23
      4: 3.11.8
      5: 0.17.0
      8:
      - 2
      - 5
      13: linux-x86_64
