wandb_version: 1

root:
  desc: null
  value: /home/disi/ml
img_folder:
  desc: null
  value: aircraft
model_name:
  desc: null
  value: efficientnetv2
data_dir:
  desc: null
  value: /home/disi/ml/datasets/aircraft
dataset_name:
  desc: null
  value: aircraft
checkpoint:
  desc: null
  value: /home/disi/ml/checkpoints/efficientnetv2_aircraft_try/efficientnetv2_aircraft_epoch20.pth
save_dir:
  desc: null
  value: /home/disi/ml/checkpoints/efficientnetv2_aircraft_try_fromepoch10
project_name:
  desc: null
  value: efficientnetv2_test
image_size:
  desc: null
  value: 224
mean:
  desc: null
  value:
  - 0.485
  - 0.456
  - 0.406
std:
  desc: null
  value:
  - 0.229
  - 0.224
  - 0.225
batch_size:
  desc: null
  value: 32
epochs:
  desc: null
  value: 20
optimizer:
  desc: null
  value: AdamW
optimizer_type:
  desc: null
  value: custom
learning_rate:
  desc: null
  value: 0.0001
weight_decay:
  desc: null
  value: 0.01
momentum:
  desc: null
  value: 0.736045219441998
criterion:
  desc: null
  value: CrossEntropyLoss
scheduler:
  desc: null
  value: true
step_size:
  desc: null
  value: 10
patience:
  desc: null
  value: 5
dropout_rate:
  desc: null
  value: 0.3317332509897824
device:
  desc: null
  value: cuda
_wandb:
  desc: null
  value:
    python_version: 3.11.8
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1716929875
    t:
      1:
      - 1
      - 41
      - 49
      - 55
      - 63
      2:
      - 1
      - 41
      - 49
      - 55
      - 63
      3:
      - 13
      - 16
      - 23
      4: 3.11.8
      5: 0.17.0
      8:
      - 2
      - 5
      13: linux-x86_64
